config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  get 'play' => 'games#play'
  patch 'play/update' => 'champs#update', as: 'champ_update'

  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')
  get 'signout' => 'sessions#destroy', as: 'signout'

end

app/models/champ.rb
class Champ < ActiveRecord::Base
	validates :name, presence: true
	validates :riot_id, presence: true
	validates :img_url, presence: true
	
	has_many :matchmakers
	has_many :rounds, through: :matchmakers

	# Handle Scoreboard Queries
	def self.marry_leaders
		return Champ.order("marry_count DESC").limit(10)
	end

	def self.sleep_leaders
		return Champ.order("sleep_count DESC").limit(10)
	end

	def self.kill_leaders
		return Champ.order("kill_count DESC").limit(10)
	end

	# ================================================ 
	# Instance Methods to handle champ db maintanence
	# ================================================ 

	# Method used in seed.rb
	def self.initial_seed
		riot_api_call['data'].each do |key, value|
			image_path = "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/" + key + "_0.jpg"
			Champ.create(name: key, riot_id: value["id"], img_url: image_path)
		end
	end

	# Makes the riot api call, refer to API documentation at the very bottom
	def self.riot_api_call
		request = "https://global.api.pvp.net/api/lol/static-data/na/v1.2/champion?api_key=" + ENV['RIOT_KEY']
		response = HTTParty.get(request)
		response_to_json = JSON.parse(response.body)

		return response_to_json
	end

	# If champ name doesn't exist in DB, create it
	def self.update_champs
		riot_api_call['data'].each do |key, value|
			if !Champ.exists?(name: key)
				image_path = "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/" + key + "_0.jpg"
				Champ.create(name: key, riot_id: value["id"], img_url: image_path)
			end
		end
	end

	# =============================
	# RIOT API DOC
	# =============================
	# /api/lol/static-data/{region}/v1.2/champion
	# Riot Documentation: https://developer.riotgames.com/api/methods#!/968/3326
	# region: na
	# locale: blank (default locale)
	# version: empty (latest version)
	# dataById: blank (false)
	# champData: none selected

	# Sample response body:
	# {
 	#   "data": {
 	#      "Aatrox": {
 	#         "id": 266,
 	#         "title": "the Darkin Blade",
 	#         "name": "Aatrox",
 	#         "key": "Aatrox"
 	#      }
 	#   	}
 	#  }

end

app/models/game.rb
class Game < ActiveRecord::Base
	validates :current_month, presence: true
	
	def self.check_for_update
		game = Game.first
		current_month = Time.now.strftime("%m")

		if current_month != game.current_month
			Champ.update_champs
			game.update(current_month: current_month)
			game.save!
		end
	end


end

app/models/matchmaker.rb
class Matchmaker < ActiveRecord::Base
	belongs_to :champ
	belongs_to :round
end

app/models/round.rb
class Round < ActiveRecord::Base
	has_many :matchmakers
	has_many :champs, through: :matchmakers

	# Randomly select 9 champions with no repeat
	def initialize_participants
		# Use pluck to efficiently return array of all champ ID's
		available_champs = Champ.all.pluck(:id)

		# Remove random champ from available_champs and add that instance to Round.champs relation
		9.times do
			selected_champ = Champ.find(available_champs.shuffle!.pop)
			self.champs << selected_champ
		end
	end

	def split_into_matches(array)
		data = {}
		data['match1'] = []
		data['match2'] = []
		data['match3'] = []
		3.times do
			data['match1'] << array.shuffle!.pop
			data['match2'] << array.shuffle!.pop
			data['match3'] << array.shuffle!.pop
		end

		return data
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true
	validates :games_counter, presence: true

	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.name = auth.info.name
	    user.oauth_token = auth.credentials.token
	    user.oauth_expires_at = Time.at(auth.credentials.expires_at)

	    if user.games_counter == nil
	    	user.games_counter = 0
	    end
	    user.save!
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
	
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

end

app/controllers/champs_controller.rb
class ChampsController < ApplicationController

	def update
		p "========"
		p "update"
		p "========"
	end

	# Strong params
	private
	def champ_params
		params.require(:champ).permit(:appearance_count, :marry_count, :sleep_count, :kill_count)
	end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	def index
		# Check if new month. If so, will run Champ.update_champs
		Game.check_for_update

		# Instance variables
		@champs_marry_leaders = Champ.marry_leaders
		@champs_sleep_leaders = Champ.sleep_leaders
		@champs_kill_leaders = Champ.kill_leaders
	end

	def scoreboard
	end

	def play
		@round = Round.new()
		# Randomly select 9 champs
		@round.initialize_participants

		@champs1 = @round.champs[0..2]
		@champs2 = @round.champs[3..5]
		@champs3 = @round.champs[6..8]
		# # Convert to array
		# array_of_champs = new_round.champs.map { |champ| champ }
		
		# # Return hash of selected champs split into 3 matches 
		# @data = new_round.split_into_matches(array_of_champs)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<h1>Welcome</h1>

<h3>Top 10 - Marry</h3>
<% @champs_marry_leaders.each do |champ| %>
	<div><%= champ.name %> : <%= champ.marry_count %> votes to marry</div>
<% end %>

<h3>Top 10 - Sleep</h3>
<% @champs_sleep_leaders.each do |champ| %>
	<div><%= champ.name %> : <%= champ.sleep_count %> votes to sleep</div>
<% end %>

<h3>Top 10 - Kill</h3>
<% @champs_kill_leaders.each do |champ| %>
	<div><%= champ.name %> : <%= champ.kill_count %> votes to kill</div>
<% end %>

<button>Play Game</button>

app/views/games/play.html.erb
<%= form_for(@round, url: champ_update_path, html: {method: "patch"}) do |f| %>
<div class="champs-container" id="round1">
	<h3 class="round-title">Round 1</h3>
	<br>
	<div class="champs-display">
		<% @champs1.each do |champ| %>
			<%= f.label champ.name %>
		<% end %>

		<%  @champs1.each do |champ| %>	
		<img class="pull-left" src=<%= champ.img_url %> >
		<% end %>
	</div>

	<div class="label-container">
		<%= label_tag(:marry, "Marry") %>
	</div>
	
	<div class="button-container">
		<%  @champs1.each do |champ| %>
		<div class="radio-container">
			<%= radio_button_tag(:marry, champ.id) %>
		</div>
		<% end %>
	</div>

	<div class="label-container">
		<%= label_tag(:sleep, "Sleep") %>
	</div>
	
	<div class="button-container">
		<%  @champs1.each do |champ| %>
		<div class="radio-container">
			<%= radio_button_tag(:sleep, champ.id) %>
		</div>
		<% end %>
	</div>

	<div class="label-container">
		<%= label_tag(:kill, "Kill") %>
	</div>
	
	<div class="button-container">
		<%  @champs1.each do |champ| %>
		<div class="radio-container">
			<%= radio_button_tag(:kill, champ.id) %>
		</div>
		<% end %>
	</div>
</div> <!-- Close round 1 -->

<div class="champs-container" id="round2">
	<h3 class="round-title">Round 2</h3>
	<br>
	<div class="champs-display">
		<% @champs2.each do |champ| %>
			<%= f.label champ.name %>
		<% end %>

		<%  @champs2.each do |champ| %>	
		<img class="pull-left" src=<%= champ.img_url %> >
		<% end %>
	</div>

	<div class="label-container">
		<%= label_tag(:marry, "Marry") %>
	</div>
	
	<div class="button-container">
		<%  @champs2.each do |champ| %>
		<div class="radio-container">
			<%= radio_button_tag(:marry, champ.id) %>
		</div>
		<% end %>
	</div>
</div> <!-- Close round 2 -->


<div class="champs-container" id="round3">
	<h3 class="round-title">Round 3</h3>
	<br>
	<div class="champs-display">
		<% @champs3.each do |champ| %>
			<%= f.label champ.name %>
		<% end %>

		<%  @champs3.each do |champ| %>	
		<img class="pull-left" src=<%= champ.img_url %> >
		<% end %>
	</div>

	<div class="label-container">
		<%= label_tag(:marry, "Marry") %>
	</div>
	
	<div class="button-container">
		<%  @champs3.each do |champ| %>
		<div class="radio-container">
			<%= radio_button_tag(:marry, champ.id) %>
		</div>
		<% end %>
	</div>
</div> <!-- Close round 3 -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MskLol</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="user_nav">
	  <% if current_user %>
	    Signed in as <strong><%= current_user.name %></strong>!
	    <%= link_to "Sign out", signout_path, id: "sign_out" %>
	  <% else %>
	    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
	  <% end %>
	</div>
<%= yield %>

</body>
</html>